### ISSUE TITLE
Exception in thread "main" java.lang.VerifyError

### ISSUE THREAD

**Issue by banshee** [jberkel/android-plugin#6] opened 2010-05-03 00:48 UTC
When I try to use the script to create a project, I get:

jamesmoore@james-moores-macbook-pro-2:/tmp$ ~/dev/android-plugin/script/create_project MyAndroidProject com.banshee.project
Exception in thread "main" java.lang.VerifyError: (class: scala/tools/nsc/MainGenericRunner$, method: main signature: ([Ljava/lang/String;)V) Can only throw Throwable objects
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
jamesmoore@james-moores-macbook-pro-2:/tmp$ 

I'm using ee96247cacaae2a24a26f5d8f531cbf5089566e3

**Comment by jberkel** [comment] 2010-05-03 20:22
which version of scala do you use?

**Comment by jberkel** [comment] 2010-05-19 22:06
can't reproduce, closing

**Closed as completed by jberkel** 2010-05-19 22:06 UTC
